### ISSUE TITLE
Add a BFS backend

### ISSUE THREAD

**Issue by AkshayAgarwal007** [HaikuArchives/Calendar#22]

**Comment by ModeenF** [comment]
Didn't I see somthing about this in another discussion? Think that the fallout was no BFS are not ment for this type of stuff but are a cool feature.

**Comment by pulkomandy** [comment]
That's not what I said. It's great to use bfs and queries for this. What I'm unconvinced about is insisting in using Tracker as a GUI for everything. Each app can provide its own way to search for things using queries instead, with a much better user experience.

Anyway, the code for this has been merged already so this issue is fixed.
