### ISSUE TITLE
Application name not translated in all catkeys files.  It is around line 98

### ISSUE THREAD

**Issue by bitigchi** [HaikuArchives/Calendar#84]
It stays as Calendar in Tracker and Deskbar.

**Comment by pulkomandy** [comment]
Yes, your help is welcome. You need to use B_TRANSLATE_SYSTEM_NAME in the appropriate places. This guide can be helpful: https://www.haiku-os.org/community/getting-involved/translating/3rdparty/

**Comment by harshit-sharma-gits** [comment]
Thanks! I'll check the resource out and get back to it.

**Comment by harshit-sharma-gits** [comment]
Hello, can you please elaborate what we are going to do, I mean do we have to change the Application name from Calendar to something else?

**Comment by scottmc** [comment]
The issue here seems to be that some of the submitted catkeys files do not have line 98 Calendar translated.  If those are updated, it works as expected.  Well at least the name on the applications Tab changes to the translated word.  Not sure about its icon or how it shows up in Deskbar.  I'm not seeing any applications names changing in my deskbar when i switch locales, but they change in preferences?  Maybe @humdingerb knows why I'm not seeing those changes.  Anyways renaming this to reflect need to get the catkeys files fixed up.

**Comment by bitigchi** [comment]
I have it translated in the Turkish cat file, but it's still not displayed in Turkish. Surely there is a bug somewhere? This issue was opened because it *was* translated.

**Comment by humdingerb** [comment]
As I wrote earlier:
"Translated app names don't appear in the Deskbar. That's a reported bug at Haiku's Trac."
